version: '3.3'

volumes:
    db_data: {}

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./:/app
    # command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    command: ["python", "./backend/debug_server.py"]
    restart: on-failure
    ports:
      - "8000:8000"

  postgres:
    image: postgres:10-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    expose:
      - 5432
